### ISSUE TITLE
Records searchable by specific funding programmes

### ISSUE THREAD

**Issue by ptamarit** [inveniosoftware/invenio-vocabularies#417]
Currently, records can be search by framework programmes:
* HE (Horizon Europe)
* H2020 (Horizon 2020)
* FP7

We should be able to also search records by specific programmes:
* Euratom Research and Training Programme (EURATOM)
* European Research Council (ERC)
* Marie Skłodowska-Curie Actions (MSCA)

**Comment by ptamarit** [comment]
# Release procedure for QA

Create 4 files with the values:

* `"/opt/invenio/var/instance/data/project-apr-2024.tar"`
* `"/opt/invenio/var/instance/data/project-may-2024.tar"`
* `"/opt/invenio/var/instance/data/project-jul-2024.tar"`
* `"/opt/invenio/var/instance/data/project-sep-2024.tar"`

```yaml
awards:
  readers:
    - type: tar
      args:
        mode: "r"
        regex: "\\.json.gz$"
        origin: "/opt/invenio/var/instance/data/project-TODO_REPLACE_ME.tar"
    - type: gzip
    - type: jsonl
  transformers:
    - type: openaire-award
  writers:
    - type: awards-service
      args:
        update: true
```

And for the CORDIS part 2 files with "FP7" OR "H2020":

```yaml
awards:
  readers:
    - type: cordis-project-http
      args:
        origin: "TODO_REPLACE_ME"
    - type: zip
      args:
        mode: "r"
        regex: "\\.xml$"
    - type: xml
      args:
        root_element: "project"
  transformers:
    - type: cordis-award
  writers:
    - type: cordis-awards-service
```

```bash
oc project zenodo-rdm-qa

oc cp config-awards-openaire-apr-2024.yaml terminal-59ff8855c8-nnwct:/opt/invenio/var/instance/data/
oc cp config-awards-openaire-may-2024.yaml terminal-59ff8855c8-nnwct:/opt/invenio/var/instance/data/
oc cp config-awards-openaire-jul-2024.yaml terminal-59ff8855c8-nnwct:/opt/invenio/var/instance/data/
oc cp config-awards-openaire-sep-2024.yaml terminal-59ff8855c8-nnwct:/opt/invenio/var/instance/data/

oc cp config-awards-cordis-fp7.yaml terminal-59ff8855c8-nnwct:/opt/invenio/var/instance/data/
oc cp config-awards-cordis-h2020.yaml terminal-59ff8855c8-nnwct:/opt/invenio/var/instance/data/

oc rsh terminal-59ff8855c8-nnwct

invenio vocabularies update --vocabulary awards --filepath /opt/invenio/var/instance/data/config-awards-openaire-apr-2024.yaml
invenio vocabularies update --vocabulary awards --filepath /opt/invenio/var/instance/data/config-awards-openaire-may-2024.yaml
invenio vocabularies update --vocabulary awards --filepath /opt/invenio/var/instance/data/config-awards-openaire-jul-2024.yaml
invenio vocabularies update --vocabulary awards --filepath /opt/invenio/var/instance/data/config-awards-openaire-sep-2024.yaml

invenio vocabularies import --vocabulary awards --filepath /opt/invenio/var/instance/data/config-awards-cordis-fp7.yaml
invenio vocabularies import --vocabulary awards --filepath /opt/invenio/var/instance/data/config-awards-cordis-h2020.yaml
TODO run HE from the jobs or the CLI with the default config.
```
